Repository SAP/cloud-sdk-java, pull requests merged in 2023-11, with the labels that each got.

#115 Fix: Silently Ignore Resilience for multiple ResilienceDecorationStrategies - Alternative
  cloudplatform/resilience/pom.xml
  cloudplatform/resilience/src/main/java/com/sap/cloud/sdk/cloudplatform/resilience/ResilienceDecorator.java
  cloudplatform/resilience/src/test/java/com/sap/cloud/sdk/cloudplatform/resilience/ResilienceDecoratorTest.java
Labels: please merge, please review

#114 Migrate OData header deduplication
  datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/request/ODataRequestGeneric.java
  datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/request/ODataRequestResultGeneric.java
  datamodel/odata-client/src/test/java/com/sap/cloud/sdk/datamodel/odata/client/request/ODataRequestResultGenericTest.java
Labels: please merge, please review

#111 Refactor: Remove CloudPlatform classes
  cloudplatform/cloudplatform-connectivity-scp-cf/pom.xml
  cloudplatform/cloudplatform-connectivity-scp-cf/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/ScpCfDestinationServiceAdapter.java
  cloudplatform/cloudplatform-connectivity-scp-cf/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/ServiceCredentialsRetriever.java
  cloudplatform/cloudplatform-connectivity-scp-cf/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/ConnectivityServiceTest.java
  cloudplatform/cloudplatform-connectivity-scp-cf/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/ScpCfDestinationServiceAdapterTest.java
  cloudplatform/cloudplatform-connectivity-scp-cf/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/ServiceCredentialsRetrieverTest.java
  cloudplatform/cloudplatform-connectivity-scp-cf/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/XsuaaSecurityTest.java
  cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpDestination.java
  cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/SecurityConfigurationStrategy.java
  cloudplatform/cloudplatform-core-dwc-cf/pom.xml
  cloudplatform/cloudplatform-core-dwc-cf/src/main/java/com/sap/cloud/sdk/cloudplatform/DwcCfCloudPlatform.java
  cloudplatform/cloudplatform-core-dwc-cf/src/main/java/com/sap/cloud/sdk/cloudplatform/DwcCfCloudPlatformFacade.java
  cloudplatform/cloudplatform-core-dwc-cf/src/main/java/com/sap/cloud/sdk/cloudplatform/MegacliteConfigurationLoader.java
  cloudplatform/cloudplatform-core-dwc-cf/src/main/resources/META-INF/services/com.sap.cloud.sdk.cloudplatform.CloudPlatformFacade
  cloudplatform/cloudplatform-core-dwc-cf/src/test/java/com/sap/cloud/sdk/cloudplatform/DwcCfCloudPlatformFacadeTest.java
  cloudplatform/cloudplatform-core-dwc-cf/src/test/java/com/sap/cloud/sdk/cloudplatform/DwcCfCloudPlatformTest.java
  cloudplatform/cloudplatform-core-dwc/src/main/java/com/sap/cloud/sdk/cloudplatform/DwcCloudPlatform.java
  cloudplatform/cloudplatform-core-scp-cf/pom.xml
  cloudplatform/cloudplatform-core-scp-cf/src/main/java/com/sap/cloud/sdk/cloudplatform/ScpCfCloudPlatform.java
  cloudplatform/cloudplatform-core-scp-cf/src/main/java/com/sap/cloud/sdk/cloudplatform/ScpCfCloudPlatformFacade.java
  cloudplatform/cloudplatform-core-scp-cf/src/main/resources/META-INF/services/com.sap.cloud.sdk.cloudplatform.CloudPlatformFacade
  cloudplatform/cloudplatform-core-scp-cf/src/test/java/com/sap/cloud/sdk/cloudplatform/ScpCfCloudPlatformTest.java
  cloudplatform/cloudplatform-core/src/main/java/com/sap/cloud/sdk/cloudplatform/CloudPlatform.java
  cloudplatform/cloudplatform-core/src/main/java/com/sap/cloud/sdk/cloudplatform/CloudPlatformAccessor.java
  cloudplatform/cloudplatform-core/src/main/java/com/sap/cloud/sdk/cloudplatform/CloudPlatformFacade.java
  cloudplatform/connectivity-dwc/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteConnectivityProxyInformationResolverTest.java
  cloudplatform/connectivity-dwc/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteDestinationFactoryTest.java
  cloudplatform/connectivity-dwc/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OutboundServiceTest.java
  cloudplatform/dwc-cf/pom.xml
  cloudplatform/pom.xml
  cloudplatform/security-scp-cf/pom.xml
  cloudplatform/security-scp-cf/src/main/java/com/sap/cloud/sdk/cloudplatform/security/K8sWorkarounds.java
  cloudplatform/security-scp-cf/src/test/java/com/sap/cloud/sdk/cloudplatform/security/AuthTokenDecoderIasTest.java
  cloudplatform/security-scp-cf/src/test/java/com/sap/cloud/sdk/cloudplatform/security/AuthTokenDecoderTest.java
  cloudplatform/tenant-scp-cf/pom.xml
  cloudplatform/tenant-scp-cf/src/main/java/com/sap/cloud/sdk/cloudplatform/tenant/ScpCfTenantFacade.java
  cloudplatform/tenant-scp-cf/src/main/java/com/sap/cloud/sdk/cloudplatform/tenant/ServiceBindingTenantExtractor.java
  cloudplatform/tenant-scp-cf/src/test/java/com/sap/cloud/sdk/cloudplatform/security/AuthTokenTenantResolvingTest.java
  cloudplatform/tenant-scp-cf/src/test/java/com/sap/cloud/sdk/cloudplatform/tenant/ScpCfTenantFacadeTest.java
  cloudplatform/tenant-scp-cf/src/test/java/com/sap/cloud/sdk/cloudplatform/tenant/ServiceBindingTenantExtractorTest.java
  module-inventory.json
  modules-bom/pom.xml
  pom.xml
  release_notes_next_major.md
  testutil/testutil-core/src/main/java/com/sap/cloud/sdk/testutil/CloudPlatformMocker.java
  testutil/testutil-core/src/main/java/com/sap/cloud/sdk/testutil/DefaultCloudPlatformMocker.java
  testutil/testutil-core/src/main/java/com/sap/cloud/sdk/testutil/MockUtil.java
Labels: please merge, please review

#112 feat: Add error handling for incorrect destination configuration in HttpClientWrapper
  cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpDestination.java
  cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpDestinationBuilderProxyHandler.java
  cloudplatform/cloudplatform-connectivity/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpDestinationBuilderProxyHandlerTest.java
  cloudplatform/connectivity-apache-httpclient4/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/HttpClientWrapper.java
  cloudplatform/connectivity-apache-httpclient5/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/ApacheHttpClient5Wrapper.java
Labels: please merge, please review

#116 feat: Add new Pull Request template for SAP Cloud SDK Java repository
  .github/PULL_REQUEST_TEMPLATE.md
Labels: please merge, please review

#118 feat: Update PR template to automatically close associated issue
  .github/PULL_REQUEST_TEMPLATE.md
Labels: please merge, please review

#120 chore: Remove legacy DwC modules
  cloudplatform/cloudplatform-core-dwc/pom.xml
  cloudplatform/cloudplatform-core-dwc/src/main/java/com/sap/cloud/sdk/cloudplatform/DefaultDwcOutboundServiceBinding.java
  cloudplatform/cloudplatform-core-dwc/src/main/java/com/sap/cloud/sdk/cloudplatform/DefaultDwcOutboundServiceMeta.java
  cloudplatform/cloudplatform-core-dwc/src/main/java/com/sap/cloud/sdk/cloudplatform/DwcOutboundProxyBinding.java
  cloudplatform/cloudplatform-core-dwc/src/main/java/com/sap/cloud/sdk/cloudplatform/DwcOutboundServiceBinding.java
  cloudplatform/cloudplatform-core-dwc/src/main/java/com/sap/cloud/sdk/cloudplatform/DwcOutboundServiceMeta.java
  cloudplatform/dwc-cf/pom.xml
  cloudplatform/pom.xml
  module-inventory.json
  modules-bom/pom.xml
  release_notes_next_major.md
Labels: do not merge, do not review

#122 fix: various PMD warnings
  .pipeline/config.yml
  cloudplatform/cloudplatform-core/src/main/java/com/sap/cloud/sdk/cloudplatform/thread/DefaultThreadContextExecutorService.java
  cloudplatform/cloudplatform-core/src/main/java/com/sap/cloud/sdk/cloudplatform/thread/LazyProperty.java
  cloudplatform/connectivity-apache-httpclient4/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/SSLContextFactory.java
  datamodel/odata-v4/odata-v4-core/src/main/java/com/sap/cloud/sdk/datamodel/odatav4/core/VdmEntity.java
  datamodel/odata-v4/odata-v4-generator/src/main/java/com/sap/cloud/sdk/datamodel/odatav4/generator/CodeModelClassGenerator.java
  datamodel/odata-v4/odata-v4-generator/src/main/java/com/sap/cloud/sdk/datamodel/odatav4/generator/EntitySetProcessor.java
  datamodel/odata-v4/odata-v4-generator/src/main/java/com/sap/cloud/sdk/datamodel/odatav4/generator/NavigationPropertyMethodsGenerator.java
  datamodel/odata-v4/odata-v4-generator/src/test/java/com/sap/cloud/sdk/datamodel/odatav4/generator/EntitySetProcessorTest.java
  datamodel/odata/odata-core/src/main/java/com/sap/cloud/sdk/datamodel/odata/helper/EntityLink.java
  datamodel/odata/odata-core/src/main/java/com/sap/cloud/sdk/datamodel/odata/helper/FluentHelperFactory.java
  datamodel/odata/odata-core/src/main/java/com/sap/cloud/sdk/datamodel/odata/helper/VdmObject.java
  datamodel/odata/odata-generator/src/main/java/com/sap/cloud/sdk/datamodel/odata/generator/NamespaceClassGenerator.java
  testutil/testutil-core/src/main/java/com/sap/cloud/sdk/testutil/ThreadContextInvocationInterceptor.java
Labels: please merge, please review

#123 fix: missing JavaDoc checkstyle warnings
  .pipeline/config.yml
  cloudplatform/cloudplatform-connectivity-scp-cf/src/main/java/com/sap/cloud/sdk/cloudplatform/exception/NoServiceBindingException.java
  cloudplatform/cloudplatform-core/src/main/java/com/sap/cloud/sdk/cloudplatform/thread/Property.java
  cloudplatform/cloudplatform-core/src/main/java/com/sap/cloud/sdk/cloudplatform/thread/ThreadContextAccessor.java
  cloudplatform/cloudplatform-core/src/main/java/com/sap/cloud/sdk/cloudplatform/thread/ThreadContextDecorator.java
  cloudplatform/cloudplatform-core/src/main/java/com/sap/cloud/sdk/cloudplatform/thread/ThreadContextDecoratorChain.java
  cloudplatform/cloudplatform-core/src/main/java/com/sap/cloud/sdk/cloudplatform/thread/ThreadContextListenerChain.java
  cloudplatform/cloudplatform-core/src/main/java/com/sap/cloud/sdk/cloudplatform/thread/exception/ThreadContextAccessException.java
  cloudplatform/cloudplatform-core/src/main/java/com/sap/cloud/sdk/cloudplatform/thread/exception/ThreadContextExecutionException.java
  cloudplatform/cloudplatform-core/src/main/java/com/sap/cloud/sdk/cloudplatform/thread/exception/ThreadContextPropertyException.java
  cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultOAuth2PropertySupplier.java
  cloudplatform/tenant/src/main/java/com/sap/cloud/sdk/cloudplatform/tenant/DefaultTenant.java
  datamodel/fluent-result/src/main/java/com/sap/cloud/sdk/result/DefaultCollectedResultCollection.java
  datamodel/fluent-result/src/main/java/com/sap/cloud/sdk/result/GsonResultElementFactory.java
  datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/ODataLiteralSerializer.java
  datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/exception/ODataException.java
  datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/expression/FilterExpressionCollection.java
  datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/expression/FilterExpressionLogical.java
  datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/expression/FilterExpressionString.java
  datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/expression/FilterExpressionTemporal.java
  datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/expression/ValueBinary.java
  datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/expression/ValueCollection.java
  datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/expression/ValueDate.java
  datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/expression/ValueDateTime.java
  datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/expression/ValueDateTimeOffset.java
  datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/expression/ValueDuration.java
  datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/expression/ValueEnum.java
  datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/expression/ValueGuid.java
  datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/expression/ValueNumeric.java
  datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/expression/ValueString.java
  datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/expression/ValueTimeOfDay.java
  datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/query/StructuredQuery.java
  datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/request/ETagSubmissionStrategy.java
  datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/request/ODataRequestResultMultipartGeneric.java
  datamodel/odata-v4/odata-v4-core/src/main/java/com/sap/cloud/sdk/datamodel/odatav4/core/BatchResponse.java
  datamodel/odata-v4/odata-v4-core/src/main/java/com/sap/cloud/sdk/datamodel/odatav4/core/VdmObject.java
  datamodel/odata/odata-core/src/main/java/com/sap/cloud/sdk/datamodel/odata/helper/EntityLink.java
  datamodel/odata/odata-core/src/main/java/com/sap/cloud/sdk/datamodel/odata/helper/ExpressionFluentHelper.java
  datamodel/odata/odata-core/src/main/java/com/sap/cloud/sdk/datamodel/odata/helper/FluentHelperBasic.java
  datamodel/odata/odata-core/src/main/java/com/sap/cloud/sdk/datamodel/odata/helper/VdmObject.java
  datamodel/odata/odata-core/src/main/java/com/sap/cloud/sdk/datamodel/odata/helper/batch/BatchResponse.java
  datamodel/odata/odata-core/src/main/java/com/sap/cloud/sdk/datamodel/odata/helper/batch/DefaultBatchResponseResult.java
  datamodel/odata/odata-core/src/main/java/com/sap/cloud/sdk/s4hana/datamodel/odata/exception/NoSuchEntityFieldException.java
  datamodel/odata/odata-generator/src/main/java/com/sap/cloud/sdk/datamodel/odata/generator/annotation/DefaultAnnotationStrategy.java
  datamodel/openapi/openapi-core/src/main/java/com/sap/cloud/sdk/services/openapi/apiclient/RFC3339DateFormat.java
  datamodel/openapi/openapi-core/src/main/java/com/sap/cloud/sdk/services/openapi/core/AbstractOpenApiService.java
  s4hana/rfc/src/main/java/com/sap/cloud/sdk/s4hana/connectivity/rfc/Fields.java
  s4hana/rfc/src/main/java/com/sap/cloud/sdk/s4hana/connectivity/rfc/JCoFieldToResultReader.java
  s4hana/rfc/src/main/java/com/sap/cloud/sdk/s4hana/connectivity/rfc/JCoTransaction.java
  s4hana/rfc/src/main/java/com/sap/cloud/sdk/s4hana/connectivity/rfc/ParameterFields.java
  s4hana/rfc/src/main/java/com/sap/cloud/sdk/s4hana/connectivity/rfc/SoapGsonResultElementFactory.java
  s4hana/rfc/src/main/java/com/sap/cloud/sdk/s4hana/connectivity/rfc/SoapRemoteFunctionRequestSerializer.java
  s4hana/s4hana-connectivity/src/main/java/com/sap/cloud/sdk/s4hana/connectivity/ErpHttpRequestExecutor.java
  s4hana/s4hana-connectivity/src/main/java/com/sap/cloud/sdk/s4hana/connectivity/Request.java
  s4hana/s4hana-core/src/main/java/com/sap/cloud/sdk/s4hana/serialization/StringBasedErpType.java
  s4hana/s4hana-core/src/main/java/com/sap/cloud/sdk/s4hana/types/Year.java
Labels: please merge, please review

#121 Refactor: Stop Splitting Header Values
  cloudplatform/cloudplatform-core/src/main/java/com/sap/cloud/sdk/cloudplatform/requestheader/DefaultRequestHeaderContainer.java
  cloudplatform/cloudplatform-core/src/main/java/com/sap/cloud/sdk/cloudplatform/requestheader/RequestHeaderContainer.java
  cloudplatform/cloudplatform-core/src/test/java/com/sap/cloud/sdk/cloudplatform/requestheader/DefaultRequestHeaderContainerTest.java
  datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/request/ODataRequestResult.java
  datamodel/odata-client/src/test/java/com/sap/cloud/sdk/datamodel/odata/client/request/ODataRequestResultTest.java
  datamodel/odata-v4/odata-v4-core/src/test/java/com/sap/cloud/sdk/datamodel/odatav4/core/HeadersHandlingTest.java
  datamodel/odata-v4/odata-v4-core/src/test/java/com/sap/cloud/sdk/datamodel/odatav4/core/ModificationResponseTest.java
  datamodel/odata/odata-core/src/test/java/com/sap/cloud/sdk/datamodel/odata/helper/ModificationResponseTest.java
  release_notes_next_major.md
Labels: please merge, please review

#126 fix: Improve exception handling in ODataRequestResultMultipartGeneric class
  datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/request/ODataRequestResultMultipartGeneric.java
  datamodel/odata-v4/odata-v4-core/src/test/java/com/sap/cloud/sdk/datamodel/odatav4/referenceservice/ODataClientBatchResponseParsingUnitTest.java
  datamodel/odata-v4/odata-v4-core/src/test/resources/ODataClientBatchResponseParsingUnitTest/BatchOnlyReadsMissingRequest.txt
  datamodel/odata-v4/odata-v4-core/src/test/resources/ODataClientBatchResponseParsingUnitTest/BatchOnlyReadsMissingResponse.txt
Labels: please merge, please review

#125 chore: Remove Dead Code
  cloudplatform/cloudplatform-connectivity-scp-cf/pom.xml
  cloudplatform/cloudplatform-connectivity-scp-cf/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/AccessToken.java
  cloudplatform/cloudplatform-connectivity-scp-cf/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/ScpCfDestinationServiceResponseProvider.java
  cloudplatform/cloudplatform-connectivity-scp-cf/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/AccessTokenTest.java
  cloudplatform/cloudplatform-core/src/main/java/com/sap/cloud/sdk/cloudplatform/WithRuntimeDependencies.java
  cloudplatform/cloudplatform-core/src/main/java/com/sap/cloud/sdk/cloudplatform/exception/ConstraintViolationException.java
  cloudplatform/cloudplatform-core/src/main/java/com/sap/cloud/sdk/cloudplatform/exception/DependencyNotFoundException.java
  cloudplatform/cloudplatform-core/src/main/java/com/sap/cloud/sdk/cloudplatform/exception/EntityAlreadyExistsException.java
  cloudplatform/cloudplatform-core/src/main/java/com/sap/cloud/sdk/cloudplatform/exception/EntityNotFoundException.java
  cloudplatform/cloudplatform-core/src/main/java/com/sap/cloud/sdk/cloudplatform/exception/StringParsingException.java
  cloudplatform/cloudplatform-core/src/main/java/com/sap/cloud/sdk/cloudplatform/exception/UnsupportedCloudFeatureException.java
  cloudplatform/security/src/main/java/com/sap/cloud/sdk/cloudplatform/security/principal/exception/PrincipalAttributeException.java
  cloudplatform/security/src/main/java/com/sap/cloud/sdk/cloudplatform/security/secret/ScpCfSecretStore.java
  cloudplatform/security/src/main/java/com/sap/cloud/sdk/cloudplatform/security/secret/ScpCfSecretStoreFacade.java
  cloudplatform/security/src/main/java/com/sap/cloud/sdk/cloudplatform/security/secret/SecretStore.java
  cloudplatform/security/src/main/java/com/sap/cloud/sdk/cloudplatform/security/secret/SecretStoreAccessor.java
  cloudplatform/security/src/main/java/com/sap/cloud/sdk/cloudplatform/security/secret/SecretStoreFacade.java
  cloudplatform/security/src/main/java/com/sap/cloud/sdk/cloudplatform/security/secret/exception/KeyStoreAccessException.java
  cloudplatform/security/src/main/java/com/sap/cloud/sdk/cloudplatform/security/secret/exception/SecretStoreAccessException.java
  release_notes_next_major.md
  s4hana/s4hana-connectivity/src/main/java/com/sap/cloud/sdk/s4hana/connectivity/exception/MissingConfigException.java
  s4hana/s4hana-connectivity/src/main/java/com/sap/cloud/sdk/s4hana/connectivity/exception/VersionNotSupportedException.java
  testutil/testutil-core/pom.xml
  testutil/testutil-core/src/main/java/com/sap/cloud/sdk/testutil/DefaultSecretStoreMocker.java
  testutil/testutil-core/src/main/java/com/sap/cloud/sdk/testutil/MockUtil.java
  testutil/testutil-core/src/main/java/com/sap/cloud/sdk/testutil/SecretStoreMocker.java
  testutil/testutil-core/src/main/java/com/sap/cloud/sdk/testutil/SecurityUtil.java
  testutil/testutil-core/src/main/java/com/sap/cloud/sdk/testutil/ThreadContextInvocationInterceptor.java
  testutil/testutil-core/src/main/java/com/sap/cloud/sdk/testutil/ThrowableAssertionUtil.java
Labels: please merge, please review

#132 chore: `dwc-cf` includes `scp-cf`
  cloudplatform/dwc-cf/pom.xml
Labels: please merge, please review

#133 fix: Update debug log message in PrincipalAccessor.java
  cloudplatform/security/src/main/java/com/sap/cloud/sdk/cloudplatform/security/principal/PrincipalAccessor.java
Labels: please merge, please review

#136 feat: Improve OAuthDestinationBuilder
  cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2DestinationBuilder.java
  cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2DestinationBuilderTest.java
  release_notes_next_major.md
Labels: please merge, please review

#131 chore: update caffeine major version
  bom/pom.xml
  pom.xml
  release_notes_next_major.md
Labels: please merge, please review

#138 Revert "chore: update caffeine major version"
  bom/pom.xml
  pom.xml
  release_notes_next_major.md
Labels: please merge, please review

#119 Minor code format improvements for log statements
  cloudplatform/caching/src/main/java/com/sap/cloud/sdk/cloudplatform/cache/CacheManager.java
  cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/AuthenticationType.java
  cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/ComplexDestinationPropertyFactory.java
  cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpDestination.java
  cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultServiceBindingDestinationLoaderChain.java
  cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationAccessor.java
  cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationLoaderChain.java
  cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationType.java
  cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationUtility.java
  cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/ErpDestinationHeaderProvider.java
  cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/ProxyType.java
  cloudplatform/servlet-jakarta/src/main/java/com/sap/cloud/sdk/cloudplatform/servletjakarta/RequestAccessorFilter.java
  cloudplatform/servlet/src/main/java/com/sap/cloud/sdk/cloudplatform/servlet/RequestAccessorFilter.java
Labels: please merge, please review

#143 fix: Update versions of olingo-v4 and olingo-v2 in pom.xml
  pom.xml
Labels: please merge, please review

#134 Add some unit tests
  cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServiceCacheTest.java
  cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultOAuth2PropertySupplierTest.java
Labels: please merge, please review

#146 Update some dependencies
  bom/pom.xml
Labels: please merge, please review

#150 chore: JUnit 5 Migration Cleanup
  datamodel/odata-v4/odata-v4-generator-maven-plugin/pom.xml
  datamodel/odata/odata-generator-maven-plugin/pom.xml
  datamodel/openapi/openapi-generator-maven-plugin/pom.xml
  pom.xml
Labels: please merge, please review

#148 readme expanded and formatted
  CONTRIBUTING.md
  README.md
Labels: please merge, please review

#149 fix: DwC Connectivity Service Auto Configuration
  cloudplatform/connectivity-dwc/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteServiceBindingAccessor.java
  cloudplatform/connectivity-dwc/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteServiceBindingAccessorTest.java
  cloudplatform/connectivity-dwc/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteServiceBindingDestinationLoaderTest.java
Labels: please merge, please review

#135 feat: SDK-Core Dependency Bundle
  archetypes/scp-cf-spring-jakarta/src/main/resources/archetype-resources/application/pom.xml
  cloudplatform/dwc-cf/pom.xml
  cloudplatform/scp-cf/pom.xml
  dependency-bundles/sdk-core/pom.xml
  module-inventory.json
  modules-bom/pom.xml
  pom.xml
  release_notes_next_major.md
Labels: please merge, please review

#127 Reduce scope of `com.sap.cloud.security:java-api` to `provided`
  cloudplatform/security/pom.xml
  cloudplatform/security/src/main/java/com/sap/cloud/sdk/cloudplatform/security/SecurityContextThreadContextDecorator.java
Labels: do not merge, please review

#151 fix: CAP API Compatibility
  cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultDestinationLoader.java
Labels: do not merge, please review

#155 chore: Parent POM Cleanup & Test Setup Improvements
  pom.xml
Labels: please merge, please review

#144 chore: Update Caffeine major version
  bom/pom.xml
  pom.xml
  release_notes_next_major.md
Labels: please merge, please review

#164 chore: Upgrade XSUAA Library to 3.3.0
  bom/pom.xml
Labels: please merge, please review

#163 chore: Remove unused DwC constants
  cloudplatform/connectivity-dwc/src/main/java/com/sap/cloud/sdk/cloudplatform/DwcHeaderUtils.java
  cloudplatform/connectivity-dwc/src/test/java/com/sap/cloud/sdk/cloudplatform/security/DwcPrincipalFacadeTest.java
Labels: please merge, please review

#162 refactor: use caffeine for caching insetad of regular resilience api
  cloudplatform/connectivity-dwc/pom.xml
  cloudplatform/connectivity-dwc/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteConnectivityProxyInformationResolver.java
  cloudplatform/connectivity-dwc/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteConnectivityProxyInformationResolverTest.java
Labels: please merge, please review

#158 General Cleanup of Leftovers
  archetypes/scp-cf-spring-jakarta/src/main/resources/archetype-resources/application/pom.xml
  bom/pom.xml
  cloudplatform/cloudplatform-connectivity-scp-cf/pom.xml
  cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpDestination.java
  cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationProperty.java
  cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationPropertyKey.java
  cloudplatform/cloudplatform-core/src/main/java/com/sap/cloud/sdk/cloudplatform/requestheader/RequestHeaderAccessor.java
  cloudplatform/cloudplatform-core/src/main/java/com/sap/cloud/sdk/cloudplatform/requestheader/RequestHeaderContainer.java
  cloudplatform/connectivity-destination-service/pom.xml
  cloudplatform/connectivity-destination-service/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationRetrievalStrategyResolver.java
  cloudplatform/connectivity-destination-service/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationService.java
  cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServicePrincipalPropagationTest.java
  cloudplatform/connectivity-dwc/pom.xml
  cloudplatform/connectivity-dwc/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DwcHeaderProvider.java
  cloudplatform/connectivity-dwc/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteServiceBindingAccessor.java
  cloudplatform/connectivity-dwc/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteServiceBindingDestinationLoaderTest.java
  cloudplatform/connectivity-dwc/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OutboundServiceTest.java
  cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2DestinationBuilder.java
  cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2HeaderProvider.java
  cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2Service.java
  cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceBindingDestinationLoader.java
  cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceBindingDestinationLoaderTest.java
  cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceTest.java
  cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OnPremTest.java
  cloudplatform/scp-cf/pom.xml
  cloudplatform/security/src/main/java/com/sap/cloud/sdk/cloudplatform/security/AuthTokenDecoder.java
  cloudplatform/servlet-jakarta/pom.xml
  cloudplatform/servlet-jakarta/src/main/java/com/sap/cloud/sdk/cloudplatform/servletjakarta/RequestAccessorFilter.java
  datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/expression/Expressions.java
  datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/expression/FilterExpressionCollection.java
  datamodel/odata-v4/odata-v4-core/pom.xml
  datamodel/odata-v4/odata-v4-core/src/test/java/com/sap/cloud/sdk/datamodel/odatav4/referenceservice/services/DefaultTrippinService.java
  module-inventory.json
  pom.xml
Labels: please merge, please review

#153 chore: Rename `scp-cf-spring-jakarta` archetype to `spring-boot3`
  .github/workflows/build-sanity.yaml
  .github/workflows/build.yaml
  .github/workflows/deploy_snapshot.yaml
  .github/workflows/prepare_release.yml
  archetypes/pom.xml
  archetypes/spring-boot3/pom.xml
  archetypes/spring-boot3/src/main/resources/META-INF/maven/archetype-metadata.xml
  archetypes/spring-boot3/src/main/resources/archetype-resources/__gitignore__
  archetypes/spring-boot3/src/main/resources/archetype-resources/application/pom.xml
  archetypes/spring-boot3/src/main/resources/archetype-resources/application/src/main/java/__packageInPathFormat__/Application.java
  archetypes/spring-boot3/src/main/resources/archetype-resources/application/src/main/java/__packageInPathFormat__/AsynchronousConfiguration.java
  archetypes/spring-boot3/src/main/resources/archetype-resources/application/src/main/java/__packageInPathFormat__/SecurityConfiguration.java
  archetypes/spring-boot3/src/main/resources/archetype-resources/application/src/main/java/__packageInPathFormat__/controllers/HelloWorldController.java
  archetypes/spring-boot3/src/main/resources/archetype-resources/application/src/main/java/__packageInPathFormat__/models/HelloWorldResponse.java
  archetypes/spring-boot3/src/main/resources/archetype-resources/application/src/main/resources/application.yml
  archetypes/spring-boot3/src/main/resources/archetype-resources/application/src/main/resources/logback-spring.xml
  archetypes/spring-boot3/src/main/resources/archetype-resources/application/src/main/resources/static/index.html
  archetypes/spring-boot3/src/main/resources/archetype-resources/application/src/test/java/__packageInPathFormat__/UnitTest.java
  archetypes/spring-boot3/src/main/resources/archetype-resources/integration-tests/pom.xml
  archetypes/spring-boot3/src/main/resources/archetype-resources/integration-tests/src/test/java/__packageInPathFormat__/HelloWorldControllerTest.java
  archetypes/spring-boot3/src/main/resources/archetype-resources/integration-tests/src/test/resources/expected.json
  archetypes/spring-boot3/src/main/resources/archetype-resources/manifest.yml
  archetypes/spring-boot3/src/main/resources/archetype-resources/pom.xml
  archetypes/spring-boot3/src/test/resources/projects/basic/archetype.properties
  archetypes/spring-boot3/src/test/resources/projects/basic/goal.txt
  module-inventory.json
Labels: please merge, please review

#166 Rollback artifact workarounds
  archetypes/spring-boot3/src/main/resources/archetype-resources/application/src/main/java/__packageInPathFormat__/Application.java
  archetypes/spring-boot3/src/main/resources/archetype-resources/pom.xml
Labels: do not merge, do not review

#167 fix: XSUAA Usage in Spring Boot Archetype
  archetypes/spring-boot3/src/main/resources/archetype-resources/application/pom.xml
  archetypes/spring-boot3/src/main/resources/archetype-resources/integration-tests/src/test/java/__packageInPathFormat__/HelloWorldControllerTest.java
  archetypes/spring-boot3/src/main/resources/archetype-resources/pom.xml
Labels: please merge, please review
