Repository SAP/cloud-sdk-java, pull requests merged in 2024-02, with the labels that each got.

#279 fix: Dependabot Release Notes Automation
  .github/workflows/dependabot-release-notes.yaml
Labels: please merge, please review

#287 fix: Snapshot Deployment
  .github/actions/deploy-snapshot/action.yaml
Labels: please merge, please review

#288 fix: BlackDuck Scan
  .github/actions/scan-with-blackduck/action.yaml
  .github/workflows/blackduck.yaml
  .github/workflows/continuous-integration.yaml
Labels: please merge, please review

#282 refactor: Remove Mentions of `Zone`
  cloudplatform/caching/src/main/java/com/sap/cloud/sdk/cloudplatform/cache/CacheManager.java
  cloudplatform/caching/src/main/java/com/sap/cloud/sdk/cloudplatform/cache/GenericCacheKey.java
  cloudplatform/caching/src/main/java/com/sap/cloud/sdk/cloudplatform/cache/SerializableCacheKey.java
  cloudplatform/caching/src/test/java/com/sap/cloud/sdk/cloudplatform/cache/CacheKeyTest.java
  cloudplatform/caching/src/test/java/com/sap/cloud/sdk/cloudplatform/cache/SerializableCacheKeyTest.java
  cloudplatform/connectivity-apache-httpclient4/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/CookieCachingTest.java
  cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServiceAdapterTest.java
  cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2Service.java
  cloudplatform/tenant/src/main/java/com/sap/cloud/sdk/cloudplatform/tenant/DefaultTenantFacade.java
  cloudplatform/tenant/src/main/java/com/sap/cloud/sdk/cloudplatform/tenant/Tenant.java
  cloudplatform/tenant/src/main/java/com/sap/cloud/sdk/cloudplatform/tenant/TenantAccessor.java
  cloudplatform/tenant/src/main/java/com/sap/cloud/sdk/cloudplatform/tenant/TenantFacade.java
  cloudplatform/tenant/src/test/java/com/sap/cloud/sdk/cloudplatform/tenant/TenantAccessorTest.java
  testutil/testutil-core/src/main/java/com/sap/cloud/sdk/testutil/DefaultTenantMocker.java
  testutil/testutil-core/src/main/java/com/sap/cloud/sdk/testutil/TenantMocker.java
Labels: please merge, please review

#289 fix: Dependabot Release Notes Generation
  .github/workflows/dependabot-release-notes.yaml
  .pipeline/scripts/dependabot-release-notes.py
Labels: please merge, please review

#278 feat: Support IAS in `OAuth2Service`
  cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/ConnectivityServiceTest.java
  cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServiceAdapterTest.java
  cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServicePrincipalPropagationTest.java
  cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/BtpServicePropertySuppliers.java
  cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultOAuth2PropertySupplier.java
  cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2DestinationBuilder.java
  cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2Service.java
  cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceBindingDestinationLoader.java
  cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/SecurityLibWorkarounds.java
  cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/ServiceBindingLibWorkarounds.java
  cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/BtpServicePropertySuppliersTest.java
  cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultOAuth2PropertySupplierTest.java
  cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2IntegrationTest.java
  cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceBindingDestinationLoaderTest.java
  cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceBuilderTest.java
  cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceTest.java
Labels: please merge, please review

#290 feat: Introduce TestContext and improve test utilities
  cloudplatform/caching/pom.xml
  cloudplatform/caching/src/test/java/com/sap/cloud/sdk/cloudplatform/cache/CacheKeyTest.java
  cloudplatform/cloudplatform-connectivity/pom.xml
  cloudplatform/cloudplatform-connectivity/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/AccessorTest.java
  cloudplatform/cloudplatform-connectivity/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpDestinationBuilderProxyHandlerTest.java
  cloudplatform/cloudplatform-connectivity/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/HttpDestinationPropertiesTest.java
  cloudplatform/connectivity-apache-httpclient4/pom.xml
  cloudplatform/connectivity-apache-httpclient4/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/CookieCachingTest.java
  cloudplatform/connectivity-apache-httpclient4/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpClientCacheTest.java
  cloudplatform/connectivity-apache-httpclient5/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultApacheHttpClient5CacheTest.java
  cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/ConnectivityServiceTest.java
  cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationRetrievalStrategyResolverTest.java
  cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServiceAdapterTest.java
  cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServiceAuthenticationTest.java
  cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServicePrincipalPropagationTest.java
  cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServiceTest.java
  cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/TokenRule.java
  cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/XsuaaTokenMocker.java
  cloudplatform/connectivity-dwc/pom.xml
  cloudplatform/connectivity-dwc/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteConnectivityProxyInformationResolverTest.java
  cloudplatform/connectivity-dwc/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteServiceBindingDestinationLoaderTest.java
  cloudplatform/connectivity-oauth/pom.xml
  cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2DestinationBuilderTest.java
  cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceTest.java
  cloudplatform/resilience4j/src/test/java/com/sap/cloud/sdk/cloudplatform/resilience4j/CacheFilterTest.java
  cloudplatform/resilience4j/src/test/java/com/sap/cloud/sdk/cloudplatform/resilience4j/RateLimiterTest.java
  cloudplatform/resilience4j/src/test/java/com/sap/cloud/sdk/cloudplatform/resilience4j/Resilience4jCachingDefaultProviderTest.java
  cloudplatform/resilience4j/src/test/java/com/sap/cloud/sdk/cloudplatform/resilience4j/Resilience4jDecorationStrategyClearCacheTest.java
  cloudplatform/resilience4j/src/test/java/com/sap/cloud/sdk/cloudplatform/resilience4j/Resilience4jDecorationStrategyTest.java
  testutil/testutil-core/pom.xml
  testutil/testutil-core/src/main/java/com/sap/cloud/sdk/testutil/AuthTokenContext.java
  testutil/testutil-core/src/main/java/com/sap/cloud/sdk/testutil/DefaultLocaleMocker.java
  testutil/testutil-core/src/main/java/com/sap/cloud/sdk/testutil/DefaultPrincipalMocker.java
  testutil/testutil-core/src/main/java/com/sap/cloud/sdk/testutil/DefaultTenantMocker.java
  testutil/testutil-core/src/main/java/com/sap/cloud/sdk/testutil/LocaleMocker.java
  testutil/testutil-core/src/main/java/com/sap/cloud/sdk/testutil/MockUtil.java
  testutil/testutil-core/src/main/java/com/sap/cloud/sdk/testutil/PrincipalContext.java
  testutil/testutil-core/src/main/java/com/sap/cloud/sdk/testutil/PrincipalMocker.java
  testutil/testutil-core/src/main/java/com/sap/cloud/sdk/testutil/TenantContext.java
  testutil/testutil-core/src/main/java/com/sap/cloud/sdk/testutil/TenantMocker.java
  testutil/testutil-core/src/main/java/com/sap/cloud/sdk/testutil/TestContext.java
  testutil/testutil-core/src/main/java/com/sap/cloud/sdk/testutil/TestContextApi.java
  testutil/testutil-core/src/test/java/com/sap/cloud/sdk/testutil/MockUtilTest.java
  testutil/testutil-core/src/test/java/com/sap/cloud/sdk/testutil/TestContextTest.java
Labels: please merge, please review

#296 feat/chore: Refactor test utilities module and update OAuth2Service
  cloudplatform/caching/pom.xml
  cloudplatform/cloudplatform-connectivity/pom.xml
  cloudplatform/connectivity-apache-httpclient4/pom.xml
  cloudplatform/connectivity-apache-httpclient5/pom.xml
  cloudplatform/connectivity-destination-service/pom.xml
  cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServiceAuthenticationTest.java
  cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServiceCacheTest.java
  cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServicePrincipalPropagationTest.java
  cloudplatform/connectivity-dwc/pom.xml
  cloudplatform/connectivity-oauth/pom.xml
  cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2Service.java
  cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceTest.java
  cloudplatform/resilience4j/pom.xml
  datamodel/odata-v4/odata-v4-core/pom.xml
  module-inventory.json
  pom.xml
  testutil/pom.xml
  testutil/src/main/java/com/sap/cloud/sdk/testutil/AuthTokenContext.java
  testutil/src/main/java/com/sap/cloud/sdk/testutil/DirectoryContentAssertionUtil.java
  testutil/src/main/java/com/sap/cloud/sdk/testutil/PrincipalContext.java
  testutil/src/main/java/com/sap/cloud/sdk/testutil/TenantContext.java
  testutil/src/main/java/com/sap/cloud/sdk/testutil/TestConfigurationError.java
  testutil/src/main/java/com/sap/cloud/sdk/testutil/TestContext.java
  testutil/src/main/java/com/sap/cloud/sdk/testutil/TestContextApi.java
  testutil/src/test/java/com/sap/cloud/sdk/testutil/TestContextTest.java
  testutil/testutil-core/.gitignore
  testutil/testutil-core/pom.xml
Labels: please merge, please review

#248 Destination: Fix certificate access to KeyStore EMPTY-PW PKCS12 file
  cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/KeyStoreReader.java
  cloudplatform/connectivity-destination-service/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationKeyStoreExtractor.java
  cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationKeyStoreExtractorTest.java
  release_notes.md
Labels: please merge, please review

#294 feat: Introduce flag for enabling anyOf/OneOf generation
  datamodel/openapi/openapi-generator-maven-plugin/src/main/java/com/sap/cloud/sdk/datamodel/openapi/generator/DataModelGeneratorMojo.java
  datamodel/openapi/openapi-generator-maven-plugin/src/test/java/com/sap/cloud/sdk/datamodel/openapi/generator/DataModelGeneratorMojoUnitTest.java
  datamodel/openapi/openapi-generator-maven-plugin/src/test/resources/DataModelGeneratorMojoUnitTest/testAdditionalPropertiesAndEnablingAnyOfOneOf/pom.xml
  datamodel/openapi/openapi-generator/src/main/java/com/sap/cloud/sdk/datamodel/openapi/generator/DataModelGenerator.java
  datamodel/openapi/openapi-generator/src/main/java/com/sap/cloud/sdk/datamodel/openapi/generator/PreprocessingStepOrchestrator.java
  datamodel/openapi/openapi-generator/src/main/java/com/sap/cloud/sdk/datamodel/openapi/generator/ValidationKeywordsPreprocessor.java
  datamodel/openapi/openapi-generator/src/main/java/com/sap/cloud/sdk/datamodel/openapi/generator/model/GenerationConfiguration.java
  datamodel/openapi/openapi-generator/src/test/java/com/sap/cloud/sdk/datamodel/openapi/generator/DataModelGeneratorIntegrationTest.java
  datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/input-spec-with-anyof-oneof/input/AggregatorNestedSchemaChild.json
  datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/input-spec-with-anyof-oneof/output/com/sap/cloud/sdk/services/anyofoneof/api/DefaultApi.java
  datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/input-spec-with-anyof-oneof/output/com/sap/cloud/sdk/services/anyofoneof/model/ChildObject1.java
  datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/input-spec-with-anyof-oneof/output/com/sap/cloud/sdk/services/anyofoneof/model/ChildObject2.java
  datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/input-spec-with-anyof-oneof/output/com/sap/cloud/sdk/services/anyofoneof/model/ChildObject3.java
  datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/input-spec-with-anyof-oneof/output/com/sap/cloud/sdk/services/anyofoneof/model/NestedChildObject.java
  datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/input-spec-with-anyof-oneof/output/com/sap/cloud/sdk/services/anyofoneof/model/RootObject.java
  datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/input-spec-with-anyof-oneof/output/com/sap/cloud/sdk/services/anyofoneof/model/RootObjectQuestionsInner.java
  release_notes.md
Labels: please merge, please review

#300 Fix compilation warning
  datamodel/openapi/openapi-core/pom.xml
  datamodel/openapi/openapi-core/src/main/java/com/sap/cloud/sdk/services/openapi/apiclient/auth/HttpBasicAuth.java
  datamodel/soap/pom.xml
Labels: please merge, please review

#303 Fix/Prepare release notes for 5.4.0
  release_notes.md
Labels: please merge, please review

#307 refactor: Remove `ServiceBindingLibWorkaround` Class
  cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/BtpServicePropertySuppliers.java
  cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2Service.java
  cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/ServiceBindingLibWorkarounds.java
  cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/BtpServicePropertySuppliersTest.java
  cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2IntegrationTest.java
Labels: please merge, please review

#302 feat: IAS Communication Scenarios
  cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/BtpServiceOptions.java
  cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/BtpServicePropertySuppliers.java
  cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2Options.java
  cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2PropertySupplier.java
  cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceBindingDestinationLoader.java
  cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/BtpServicePropertySuppliersTest.java
  cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceBindingDestinationLoaderTest.java
  cloudplatform/connectivity-oauth/src/test/resources/IdentityAuthenticationPropertySupplier/README.md
  cloudplatform/connectivity-oauth/src/test/resources/IdentityAuthenticationPropertySupplier/certificate.crt
  cloudplatform/connectivity-oauth/src/test/resources/IdentityAuthenticationPropertySupplier/csr.pem
  cloudplatform/connectivity-oauth/src/test/resources/IdentityAuthenticationPropertySupplier/privatekey.pem
Labels: please merge, please review

#313 fix: [OpenAPI] Fix Typo in OpenAPI Generator
  datamodel/openapi/openapi-generator-maven-plugin/src/test/resources/DataModelGeneratorMojoUnitTest/testAdditionalPropertiesAndEnablingAnyOfOneOf/pom.xml
  datamodel/openapi/openapi-generator/src/main/java/com/sap/cloud/sdk/datamodel/openapi/generator/ValidationKeywordsPreprocessor.java
Labels: please merge, please review

#315 fix: [DevOps] Fix Broken Maven Plugin Tests and Ban JUnit4
  cloudplatform/connectivity-destination-service/pom.xml
  cloudplatform/connectivity-oauth/pom.xml
  cloudplatform/security/pom.xml
  cloudplatform/security/src/test/java/com/sap/cloud/sdk/cloudplatform/security/principal/OAuth2AuthTokenPrincipalExtractorTest.java
  cloudplatform/tenant/pom.xml
  datamodel/odata-v4/odata-v4-generator-maven-plugin/pom.xml
  datamodel/odata-v4/odata-v4-generator-maven-plugin/src/test/java/com/sap/cloud/sdk/datamodel/odatav4/generator/DataModelGeneratorMojoTest.java
  datamodel/odata/odata-generator-maven-plugin/pom.xml
  datamodel/odata/odata-generator-maven-plugin/src/test/java/com/sap/cloud/sdk/datamodel/odata/generator/DataModelGeneratorMojoTest.java
  datamodel/openapi/openapi-generator-maven-plugin/pom.xml
  datamodel/openapi/openapi-generator-maven-plugin/src/test/java/com/sap/cloud/sdk/datamodel/openapi/generator/DataModelGeneratorMojoIntegrationTest.java
  datamodel/openapi/openapi-generator-maven-plugin/src/test/java/com/sap/cloud/sdk/datamodel/openapi/generator/DataModelGeneratorMojoUnitTest.java
  datamodel/openapi/openapi-generator-maven-plugin/src/test/resources/DataModelGeneratorMojoIntegrationTest/sodastore/output/com/sap/cloud/sdk/datamodel/rest/sodastore/model/NewSoda.java
  datamodel/openapi/openapi-generator-maven-plugin/src/test/resources/DataModelGeneratorMojoIntegrationTest/sodastore/output/com/sap/cloud/sdk/datamodel/rest/sodastore/model/Soda.java
  datamodel/openapi/openapi-generator-maven-plugin/src/test/resources/DataModelGeneratorMojoIntegrationTest/sodastore/output/com/sap/cloud/sdk/datamodel/rest/sodastore/model/UpdateSoda.java
  datamodel/openapi/openapi-generator-maven-plugin/src/test/resources/DataModelGeneratorMojoUnitTest/testInvocationWithUnexpectedApiMaturity/pom.xml
  pom.xml
Labels: please merge, please review

#320 fix: Fix Surefire reports on Dependabots PRs
  .github/workflows/continuous-integration.yaml
Labels: please merge, please review

#326 fix: [HttpClient] Fix Destination Reference in ApacheHttpClient5Wrapper
  cloudplatform/connectivity-apache-httpclient5/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/ApacheHttpClient5Wrapper.java
  cloudplatform/connectivity-apache-httpclient5/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultApacheHttpClient5Cache.java
  cloudplatform/connectivity-apache-httpclient5/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultApacheHttpClient5CacheTest.java
  cloudplatform/connectivity-apache-httpclient5/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/HttpClientWrapperTest.java
  release_notes.md
Labels: bug, please merge, please review

#327 fix: [Destinations] Allow for Custom Proxy Config in ON_PREMISE Destinations
  cloudplatform/connectivity-dwc/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteServiceBindingDestinationLoader.java
  cloudplatform/connectivity-dwc/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteServiceBindingDestinationLoaderTest.java
  cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceBindingDestinationLoader.java
  cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceBindingDestinationLoaderTest.java
  release_notes.md
Labels: please merge, please review

#330 chore: Deprecate `RfcDestination` and associated usages
  cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultRfcDestination.java
  cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/Destination.java
  cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/EnvVarDestinationLoader.java
  cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/RfcDestination.java
  cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/RfcDestinationProperties.java
  cloudplatform/cloudplatform-connectivity/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/CustomDestinationRegistrationTest.java
  cloudplatform/cloudplatform-connectivity/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultDestinationTest.java
  cloudplatform/cloudplatform-connectivity/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultRfcDestinationTest.java
  cloudplatform/connectivity-destination-service/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServiceFactory.java
  cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServiceFactoryTest.java
  cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServiceTest.java
  release_notes.md
Labels: please merge, please review

#317 chore: Remove automated release notes for dependabot
  .github/workflows/dependabot-release-notes.yaml
  .pipeline/scripts/dependabot-release-notes.py
Labels: please merge, please review

#335 feat: Remove dependency updates section from release notes and automation script
  .pipeline/scripts/release_notes_automation.py
  .pipeline/scripts/release_notes_template.md
  docs/how-to/release.md
  release_notes.md
Labels: please review
